### Merging Arrays in NumPy
You can merge arrays along a specific axis using NumPy’s concatenate function. The axis parameter determines the dimension along which the arrays are joined. It is important that all arrays have the same number of dimensions and match in length across all axes except the axis used for concatenation.

Below are examples demonstrating array concatenation:

In [12]:
import numpy as np  

a1 = np.array([[1, 2, 3], [3, 4, 5]])  
a2 = np.array([[2, 2, 3], [1, 2, 5]])  

print("Array 1:\n", a1)  
print("Array 2:\n", a2)  

#By default, concatenate joins arrays along axis=0:
a3= np.concatenate((a1, a2))  
print("Array 3:\n", a3) 

a4= np.concatenate((a1, a2), axis=1) 
print("Array 4:\n", a4) 

Array 1:
 [[1 2 3]
 [3 4 5]]
Array 2:
 [[2 2 3]
 [1 2 5]]
Array 3:
 [[1 2 3]
 [3 4 5]
 [2 2 3]
 [1 2 5]]
Array 4:
 [[1 2 3 2 2 3]
 [3 4 5 1 2 5]]


***Handling Dimension Mismatches***

If an array does not match the required dimensions, an error occurs. For example:



In [18]:
a5 = np.array([2, 2, 3])  
np.concatenate((a1, a5), axis=0)  
#This raises a ValueError because a5 is 1D, while a1 is 2D.


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [20]:

#To resolve this, reshape a5 to match the required dimensions:

a5_reshaped = a5.reshape(1, 3)  
np.concatenate((a1, a5_reshaped), axis=0)  

array([[1, 2, 3],
       [3, 4, 5],
       [2, 2, 3]])

### Practice Exercise 1

We will find the nearest major US city to the geographical center of the contiguous United States.The geographical center of the contiguous US is approximately (39.8283° N, 98.5795° W). Using a dataset of major US cities and their coordinates, find the city that is closest to this center based on Euclidean distance.


* Use Pandas to read the dataset from a CSV file.
* Convert the relevant latitude/longitude columns to a NumPy array.
* Use broadcasting to calculate the Euclidean distance of each city from the center.
* Find the city with the minimum distance.


In [40]:
import pandas as pd
import numpy as np

# Load the dataset of major US cities with coordinates
cities = pd.read_csv("UScities.csv")
print(cities)


             City  Latitude  Longitude
0        New York   40.7128   -74.0060
1     Los Angeles   34.0522  -118.2437
2         Chicago   41.8781   -87.6298
3         Houston   29.7604   -95.3698
4         Phoenix   33.4484  -112.0740
5    Philadelphia   39.9526   -75.1652
6     San Antonio   29.4241   -98.4936
7       San Diego   32.7157  -117.1611
8          Dallas   32.7767   -96.7970
9        San Jose   37.3382  -121.8863
10         Austin   30.2672   -97.7431
11   Jacksonville   30.3322   -81.6557
12     Fort Worth   32.7555   -97.3308
13       Columbus   39.9612   -82.9988
14  San Francisco   37.7749  -122.4194
15      Charlotte   35.2271   -80.8431
16   Indianapolis   39.7684   -86.1581
17        Seattle   47.6062  -122.3321
18         Denver   39.7392  -104.9903
19     Washington   38.9072   -77.0369
20         Boston   42.3601   -71.0589
21        El Paso   31.7619  -106.4850
22      Nashville   36.1627   -86.7816
23        Detroit   42.3314   -83.0458
24  Oklahoma City   35.46

In [ ]:
# Now, find The names of the top 10 closest cities to the center of the US.
# Store a NumPy array containing their coordinates.
# Use NumPy’s concatenate() function to stack the coordinates...

### Example 2 ###

You're analyzing the weight and height of dachshunds from different breeders. The dataset includes measurements of dachshunds and a comparison of average sizes across breeders.

Read the data using Pandas, clean it, and find the breeder with the most consistent dachshund sizes (i.e., the breeder with the lowest standard deviation in height and weight).Use NumPy to calculate the average weight and height of dachshunds from different breeders and determine which breeder has the largest average dachshund.

